#!/usr/bin/env python3
"""Regenerates _perfetto_trace_widget_inline.py from the real widget.py.

`marimo export html-wasm` can't `pip install perfetto-trace-widget` in the
browser -- it isn't published to PyPI, and Pyodide/micropip only installs
from PyPI (or an explicit wheel URL) by default. But a notebook's own
directory is mounted into the in-browser filesystem, so a *local* sibling
module imports with zero package-manager involvement. This script embeds
the built widget.js (base64, to avoid escaping headaches -- it's minified
JS full of quotes and backticks) directly into a copy of widget.py's
logic, producing a single dependency-free file that marimo_demo_wasm.py
imports directly instead of going through the real package.

This is a workaround for one specific constraint (no PyPI publish yet),
not a design endorsement -- once this package is published, delete this
script, _perfetto_trace_widget_inline.py, and marimo_demo_wasm.py, and
have examples/marimo_demo.py's `marimo export html-wasm` note point
users at a plain `pip install perfetto-trace-widget` instead.

Regenerate after anything under src/perfetto_trace_widget/ changes:

    python examples/generate_inline_widget.py
"""

from __future__ import annotations

import base64
import pathlib

_ROOT = pathlib.Path(__file__).parent.parent
_WIDGET_PY = _ROOT / "src" / "perfetto_trace_widget" / "widget.py"
_WIDGET_JS = _ROOT / "src" / "perfetto_trace_widget" / "static" / "widget.js"
_OUT = pathlib.Path(__file__).parent / "_perfetto_trace_widget_inline.py"

_BANNER = '''\
"""PerfettoTraceWidget, with widget.js inlined -- for html-wasm export only.

GENERATED by generate_inline_widget.py from widget.py + the built
widget.js -- do not edit by hand, regenerate instead. See that script's
docstring for why this file exists (short version: this package isn't on
PyPI yet, so `marimo export html-wasm` can't `pip install` it -- this
sibling-importable, dependency-free copy sidesteps that entirely).

For every other use case (a normal Python env, Jupyter, local marimo
edit/run against a real kernel), `pip install perfetto-trace-widget` and
import `perfetto_trace_widget` instead -- this file is only for the
static export path.
"""

'''


def main() -> None:
    source = _WIDGET_PY.read_text()

    # Drop the original module docstring (replaced by _BANNER above) --
    # it's the first '''...''' or """...""" block in the file.
    assert source.startswith('"""'), "widget.py must start with a docstring"
    end = source.index('"""', 3) + 3
    source = source[end:].lstrip("\n")

    # Drop the package-relative static-file lookup -- the generated module
    # embeds the built JS directly instead of reading it off disk.
    assert "import pathlib\n" in source
    source = source.replace("import pathlib\n", "", 1)
    assert '_STATIC_DIR = pathlib.Path(__file__).parent / "static"\n' in source
    source = source.replace(
        '_STATIC_DIR = pathlib.Path(__file__).parent / "static"\n', "", 1
    )
    assert '_esm = _STATIC_DIR / "widget.js"' in source
    source = source.replace(
        '_esm = _STATIC_DIR / "widget.js"', "_esm = _WIDGET_JS", 1
    )

    js_b64 = base64.b64encode(_WIDGET_JS.read_bytes()).decode("ascii")
    # Wrap the base64 payload so the generated file doesn't have a single
    # multi-hundred-column line.
    wrapped = "\n".join(js_b64[i : i + 100] for i in range(0, len(js_b64), 100))
    js_lines = "\n    ".join(f'"{chunk}"' for chunk in wrapped.split("\n"))

    assert "import json\n" in source
    source = source.replace("import json\n", "import base64\nimport json\n", 1)

    # Insert the embedded JS constant right after the import block, before
    # the first module-level constant (_DTYPE_MAP).
    marker = "_DTYPE_MAP = {"
    assert marker in source
    js_block = (
        f"_WIDGET_JS_B64 = (\n    {js_lines}\n)\n"
        '_WIDGET_JS = base64.b64decode(_WIDGET_JS_B64).decode("utf-8")\n\n\n'
    )
    source = source.replace(marker, js_block + marker, 1)

    out = _BANNER + source
    _OUT.write_text(out)
    print(f"wrote {_OUT} ({len(out)} bytes, embedding {len(js_b64)} b64 chars)")


if __name__ == "__main__":
    main()
